# SPDX-License-Identifier: BSD-2-Clause
# ThinkPad A475: mic-mute key arrives as an ACPI event, not as an X key
notify 10 {
	match "system"		"ACPI";
	match "subsystem"	"IBM";
	match "notify"		"0x1b";
	action "/usr/local/libexec/thinkpad-micmute";
};
